### ISSUE TITLE
Components hierarchy

### ISSUE THREAD

**Issue by KyrietS** [KyrietS/CodeMap#15]
- https://skypjack.github.io/2019-06-25-ecs-baf-part-4/
- https://skypjack.github.io/2019-08-20-ecs-baf-part-4-insights/
- https://gamedev.stackexchange.com/questions/174319/dealing-with-more-complex-entities-in-an-ecs-architecture/174327#174327

**TODO:**
- [x] `GlobalTransform` matrix and use it everywhere instead of local transform values
- [x] Update `GlobalTransform` every frame
- [x] Remove `Origin` from `LineSegment` and `Arrowhead`
- [x] Make sure `Focusable` still works
- [ ] Change the way arrows are constructed. Now `LineSegment` and `Arrowhead` should be in a separate entities with common parent.
